#!/bin/bash

ayuda_src () {
bot_retorno="🔹 <b>MENÚ DE AYUDA</b> 🔹\n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🆔 <b>/ID</b>\n muestra tu ID de telegram\n para tener acceso al /keygen\n deves enviar tu ID al admin @Rufu99\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🔑 <b>(Boton) Keygen</b>\n genera una key para\n el instalador del script\n para tener acceso\n deves enviar tu ID al admin @Rufu99\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="📋 <b>/menu</b>\n muestra el menu\n de comandos disponibles\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="❓ <b>/ayuda</b>\n muestra este menu de ayuda\n"
			 bot_retorno+="$LINE\n"
		 else
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🆔 <b>/ID</b>\n muestra tu ID de telegram\n para tener acceso al /keygen\n deves enviar tu ID al admin @Rufu99\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🔑 <b>(Boton) Keygen</b>\n genera una key para\n el instalador del script\n para tener acceso\n deves enviar tu ID al admin @Rufu99\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="⚙️ <b>/instal</b>\n muestra el link de instalacion\n del script para usar tu key\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="📋 <b>/menu</b>\n muestra el menu\n de comandos disponibles\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="❓ <b>/ayuda</b>\n muestra este menu de ayuda\n"
			 bot_retorno+="$LINE\n"
		 fi
	 else
		 bot_retorno+="$LINE\n"
		 bot_retorno+="📊 <b>/infosys</b>\n muestra informacion del sistema\n Ram, Cpu, Fecha y Hora\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="🆔 <b>/ID</b>\n muestra tu ID de telegram\n para tener acceso al /keygen\n deves enviar tu ID al admin @Rufu99\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="➕ <b>/add</b>\n añade nuevo ID\n para dar acceso /keygen\n <u>modo de uso</u>\n /add 123456789\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="➖ <b>/del</b>\n elimina los ID\n antes deves usar /list\n <u>modo de uso</u>\n /del 4\n /del 6\n etc\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="📜 <b>/list</b>\n muestra una lista de id\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="🔑 <b>(Boton) Keygen</b>\n genera una key para\n el instalador del script\n para tener acceso\n deves enviar tu ID al admin @Rufu99\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="⚙️ <b>/instal</b>\n muestra el link de instalacion\n del script para usar tu key\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="🔌 <b>/power</b>\n poner o sacar de linea el generador\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="📋 <b>/menu</b>\n muestra el menu\n de comandos disponibles\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="❓ <b>/ayuda</b>\n muestra este menu de ayuda\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="🧹 <b>/cache</b>\n limpia el cache contenido en la ram\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="♻️ <b>/reboot</b>\n Reinicia el servidor vps\n"
		 bot_retorno+="$LINE\n"
	 fi
msj_fun
}
