#!/bin/bash
# -*- ENCODING: UTF-8 -*-

SCPT_DIR="/etc/SCRIPT"
DIR="/etc/http-shell"
LIST="HexGen"

mkdir -p "$SCPT_DIR"
mkdir -p "$DIR"

meu_ip_fun() {
    MIP=$(ip addr | grep 'inet ' | grep -v inet6 | \
        grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
        grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)

    MIP2=$(wget -qO- --timeout=5 ipv4.icanhazip.com)

    if [[ -n "$MIP2" ]]; then
        IP="$MIP2"
    else
        IP="$MIP"
    fi
}

ofus() {
    unset txtofus

    number=$(expr length "$1")

    for ((i=1; i<=number; i++)); do

        txt[$i]=$(echo "$1" | cut -b "$i")

        case ${txt[$i]} in
            ".") txt[$i]="*";;
            "*") txt[$i]=".";;
            "1") txt[$i]="@";;
            "@") txt[$i]="1";;
            "2") txt[$i]="?";;
            "?") txt[$i]="2";;
            "4") txt[$i]="%";;
            "%") txt[$i]="4";;
            "-") txt[$i]="K";;
            "K") txt[$i]="-";;
        esac

        txtofus+="${txt[$i]}"
    done

    echo "$txtofus" | rev
}

fun_list() {
    KEY="$1"
    mkdir -p "${DIR}/${KEY}"
    echo "$LIST" > "${DIR}/${KEY}/${LIST}"
    nombrevalue="${chatuser:-${message_from_id:-${callback_query_from_id:-0}}}"
    echo "$nombrevalue" > "${DIR}/${KEY}.name"
    if [[ -n "$IPFIX" ]]; then
        echo "$IPFIX" > "${DIR}/${KEY}/keyfixa"
    fi
    at now + 4 hours <<< "rm -rf '${DIR}/${KEY}' '${DIR}/${KEY}.name'" 2>/dev/null
}

gerar_key() {

    meu_ip_fun

    valuekey="$(date +%s%N | md5sum | head -c10)"
    valuekey+="$(echo $((RANDOM * 10)) | head -c5)"

    fun_list "$valuekey"

    keyfinal="${LIST}/$(ofus "${IP}:8888/${valuekey}")"

    local bot_retorno="$LINE\n"

    bot_retorno+="Hex Auto Script By JotchuaDevzZ\n"
    bot_retorno+="✅ Key Generada Con Exito! ✅\n"
    bot_retorno+="$LINE\n"
    bot_retorno+="<code>${keyfinal}</code>\n"
    bot_retorno+="$LINE\n"
    bot_retorno+="⚠️ Sistemas recomendados: Ubuntu 20.04 y 22.04\n"
    bot_retorno+="$LINE\n"

    bot_retorno+="<pre>sudo apt update -y; apt upgrade -y; wget -qO install.sh https://raw.githubusercontent.com/JotchuaDevz/Porno-OS/refs/heads/main/install.sh; chmod +x install.sh; ./install.sh</pre>\n"

    bot_retorno+="Esta key se autodestruira en 4hs\n"
    bot_retorno+="pasado este tiempo deve generar una nueva key.\n"

    bot_retorno+="$LINE\n"

    msj_fun
}
