#!/bin/bash

menu_src () {
bot_retorno="🔹 <b>PANEL DE COMANDOS</b> 🔹\n"

unset usadas
usadas="$(cat /etc/http-instas)"
[[ ! $usadas ]] && k_used="0" || k_used="$usadas"

	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🔑 Keys usadas: <b>$k_used</b>\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🆔 /ID — muestra tu ID\n"
			 bot_retorno+="📋 /menu — muestra este menu\n"
			 bot_retorno+="❓ /ayuda — ayuda de los comandos\n"
			 bot_retorno+="$LINE\n"
			 msj_fun
		 else
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🔑 Keys usadas: <b>$k_used</b>\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="🆔 /ID — muestra tu ID\n"
			 bot_retorno+="⚙️ /instal — link de instalacion\n"
			 bot_retorno+="📋 /menu — muestra este menu\n"
			 bot_retorno+="❓ /ayuda — ayuda de los comandos\n"
			 bot_retorno+="$LINE\n"
			 menu_print
		 fi
		 
	 else
		 unset PID_GEN
		 if systemctl is-active --quiet hexgen-http.service; then
			 PID_GEN='🟢 Online'
		 else
			 PID_GEN='🔴 Offline'
		 fi

		 bot_retorno+="$LINE\n"
		 bot_retorno+="🖥️ Generador: $PID_GEN\n"
		 bot_retorno+="🔑 Keys usadas: <b>$k_used</b>\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="📊 /infosys — info del sistema\n"
		 bot_retorno+="📜 /list — lista de ID permitidas\n"
		 bot_retorno+="⚙️ /instal — link de instalacion\n"
		 bot_retorno+="📋 /menu — muestra este menu\n"
		 bot_retorno+="❓ /ayuda — ayuda de los comandos\n"
		 bot_retorno+="🧹 /cache — limpiar cache RAM\n"
		 bot_retorno+="🔄 /update — actualiza el BotGen\n"
		 bot_retorno+="♻️ /reboot — reinicia el servidor vps\n"
		 bot_retorno+="$LINE\n"
		 menu_print
	 fi	
}
